---
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.*'
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: whereamifrom
          token: ${{ secrets.GITHUB_TOKEN }}
